openapi: v3.0.x
info:
  title: Lost & Found QR Platform API
  version: 0.1
servers:
  - url: https://api.lostfound.example
paths:
  /tag/{hash}:
    get:
      summary: "Lookup a tag by hash (Tag Scan Entry Point)"
      operationId: tagRedirect
      description: >
        Returns metadata and status for a scanned tag. No authentication required.
        Handles 'unclaimed' (no owner yet) and 'claimed' (owned) states.
        Does not expose owner contact or sensitive info.
      parameters:
        - name: hash
          in: path
          required: true
          schema:
            type: string
      responses:
        '302':
          description: "Redirect to Tag UI"
          headers:
            Location:
              description: "Destination URL of the UI, including Tag-Hash"
              schema:
                type: string
                example: "/ui/?tag={hash}"
        '404':
          description: Tag not found (invalid or deleted)
  
  /api/owner:
components:
  schemas:
    TagScanResponse:
      type: object
      properties:
        tagId:
          type: string
          description: "The unique ID of the tag (reference, not directly linkable to user data)"
        status:
          type: string
          enum: [unclaimed, claimed]
          description: "'unclaimed' (no owner) or 'claimed' (owner exists)"
        currentState:
          type: string
          enum: [not_lost, lost]
          nullable: true
          description: "Tag's current status; present only if 'claimed'."
        description:
          type: string
          nullable: true
          description: "Optional, privacy-friendly tag description (if set by owner)."
        claimable:
          type: boolean
          description: "Whether the tag can be claimed after login. True when status is 'unclaimed'."
        allowedActions:
          type: array
          items:
            type: string
            enum: [claim, contact, report]
          description: "UI hints: what actions are currently available for the user."
        infoText:
          type: string
          description: "User-facing explanation for current tag state, not containing any PI."
      required:
        - tagId
        - status
        - claimable
        - allowedActions
        - infoText