[tool.poetry]
name = "shared"
version = "0.1.0"
description = "Common models, validation, and utilities for Lost & Found Lambdas"
authors = ["Dein Name <dein@email.de>"]

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
mypy = "^1.0"