openapi: 3.0.1
info:
  title: Lost & Found QR Platform API
  version: "0.1"
servers:
  - url: https://api.lostfound.example
paths:
  /owner/onboarding:
    post:
      summary: Owner Registration / Onboarding
      operationId: ownerOnboarding
      requestBody:
        description: "User request to register or continue onboarding, discriminator should be 'onboarding_init' or 'onboarding_public_key'"
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/schemas.yaml#/components/schemas/OnboardingRequest"
      responses:
        "201":
          description: Owner created or onboarding step completed
          content:
            application/json:
              schema:
                $ref: "./schemas/schemas.yaml#/components/schemas/APIResponseModel"

  /owner/login:
    post:
      summary: Owner Auth (Challenge/Response)
      operationId: ownerLogin
      security:
        - {}
        - SessionTokenAuth: []
      requestBody:
        description: "User login request, discriminator should be 'login_challenge' or 'login_response'"
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/schemas.yaml#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Auth Step (challenge issued or session granted)
          content:
            application/json:
              schema:
                $ref: "./schemas/schemas.yaml#/components/schemas/APIResponseModel"

  /owner/refresh:
    post:
      summary: Refresh a session token
      operationId: ownerSessionRefresh
      security:
        - SessionTokenAuth: []
      requestBody:
        description: "User request to refresh session token, discriminator should be 'session_refresh'"
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/schemas.yaml#/components/schemas/SessionRefreshRequest"

      responses:
        "200":
          description: Refreshed session token
          content:
            application/json:
              schema:
                $ref: "./schemas/schemas.yaml#/components/schemas/APIResponseModel"

  /owner/logout:
    post:
      summary: Invalidate session token (logout)
      operationId: ownerLogout
      security:
        - SessionTokenAuth: []
      responses:
        "204":
          description: Logged out

  /owner/delete:
    post:
      summary: Owner account delete (self-service)
      operationId: ownerDelete
      security:
        - SessionTokenAuth: []
      responses:
        "204":
          description: Account deleted

  /owner/storage:
    post:
      summary: Store or retrieve encrypted private data storage
      operationId: ownerStorage
      security:
        - SessionTokenAuth: []
      requestBody:
        description: "User request to store or retrieve encrypted private data, discriminator should be 'owner_storage'"
        content:
          application/json:
            schema:
              $ref: "./schemas/schemas.yaml#/components/schemas/OwnerStorageWriteRequest"
      responses:
        "200":
          description: Stored or retrieved encrypted private data storage
          content:
            application/json:
              schema:
                $ref: "./schemas/schemas.yaml#/components/schemas/APIResponseModel"
    get:
      summary: Retrieve encrypted private data storage
      operationId: ownerStorageGet
      security:
        - SessionTokenAuth: []
      responses:
        "200":
          description: Retrieved encrypted private data storage
          content:
            application/json:
              schema:
                $ref: "./schemas/schemas.yaml#/components/schemas/APIResponseModel"
components:
  securitySchemes:
    SessionTokenAuth:
      type: apiKey
      in: header
      name: Session-Token
      description: Session token for authentication (starts with 'sessiontok_')
