openapi: 3.0.1
info:
  title: Lost & Found QR Platform API
  version: "0.1"
servers:
  - url: https://api.lostfound.example

tags:
  - name: Owner
    description: End-user (owner) account management and authentication

paths:
  /owner/onboarding:
    post:
      tags:
        - Owner
      summary: Owner Registration / Onboarding
      operationId: ownerOnboarding
      requestBody:
        description: "User request to register or continue onboarding, discriminator should be 'onboarding_init' or 'onboarding_public_key'"
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/schemas.yaml#/components/schemas/OnboardingRequest"
      parameters:
        - name: Onetime-Token
          in: header
          description: Onetime token received in previous onboarding step (required for onboarding_public_key)
          required: false
          schema:
            type: string
      responses:
        "201":
          description: Owner created or onboarding step completed
          headers:
            Onetime-Token:
              description: Onetime token for next onboarding step (sent after onboarding_init)
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "./schemas/schemas.yaml#/components/schemas/APIResponseModel"

  /owner/login:
    post:
      tags:
        - Owner
      summary: Owner Auth (Challenge/Response)
      operationId: ownerLogin
      security:
        - {}
        - SessionTokenAuth: []
      requestBody:
        description: "User login request, discriminator should be 'login_challenge' or 'login_response'"
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/schemas.yaml#/components/schemas/LoginRequest"
      parameters:
        - name: Onetime-Token
          in: header
          description: Onetime token received in previous login challenge (required for login_response)
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Auth Step (challenge issued or session granted)
          headers:
            Session-Token:
              description: Session token issued after successful login (starts with 'sessiontok_')
              schema:
                type: string
            Onetime-Token:
              description: Onetime token for next login step (sent after login_challenge)
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "./schemas/schemas.yaml#/components/schemas/APIResponseModel"

  /owner/refresh:
    post:
      tags:
        - Owner
      summary: Refresh a session token
      operationId: ownerSessionRefresh
      security:
        - SessionTokenAuth: []
      requestBody:
        description: "User request to refresh session token, discriminator should be 'session_refresh'"
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/schemas.yaml#/components/schemas/SessionRefreshRequest"

      responses:
        "200":
          description: Refreshed session token
          content:
            application/json:
              schema:
                $ref: "./schemas/schemas.yaml#/components/schemas/APIResponseModel"

  /owner/logout:
    post:
      tags:
        - Owner
      summary: Invalidate session token (logout)
      operationId: ownerLogout
      security:
        - SessionTokenAuth: []
      responses:
        "204":
          description: Logged out

  /owner:
    get:
      tags:
        - Owner
      summary: Get owner account info/status
      operationId: ownerGet
      security:
        - SessionTokenAuth: []
      responses:
        "200":
          description: Owner account info or status
          content:
            application/json:
              schema:
                $ref: "./schemas/schemas.yaml#/components/schemas/APIResponseModel"
    delete:
      tags:
        - Owner
      summary: Delete owner account (challenge/confirm)
      operationId: ownerDeleteAccount
      security:
        - SessionTokenAuth: []
      requestBody:
        description: "Owner account delete request (challenge/confirm)"
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/schemas.yaml#/components/schemas/DeleteOwnerRequest"
      responses:
        "200":
          description: Account deleted (confirmation)
          content:
            application/json:
              schema:
                $ref: "./schemas/schemas.yaml#/components/schemas/APIResponseModel"
        "204":
          description: Account deleted (no content)

  /owner/storage:
    post:
      tags:
        - Owner
      summary: Store or retrieve encrypted private data storage
      operationId: ownerStorage
      security:
        - SessionTokenAuth: []
      requestBody:
        description: "User request to store or retrieve encrypted private data, discriminator should be 'owner_storage'"
        content:
          application/json:
            schema:
              $ref: "./schemas/schemas.yaml#/components/schemas/OwnerStorageWriteRequest"
      responses:
        "200":
          description: Stored or retrieved encrypted private data storage
          content:
            application/json:
              schema:
                $ref: "./schemas/schemas.yaml#/components/schemas/APIResponseModel"
    get:
      tags:
        - Owner
      summary: Retrieve encrypted private data storage
      operationId: ownerStorageGet
      security:
        - SessionTokenAuth: []
      responses:
        "200":
          description: Retrieved encrypted private data storage
          content:
            application/json:
              schema:
                $ref: "./schemas/schemas.yaml#/components/schemas/APIResponseModel"
    delete:
      tags:
        - Owner
      summary: Delete owner private storage (challenge/confirm)
      operationId: ownerStorageDelete
      security:
        - SessionTokenAuth: []
      requestBody:
        description: "Owner storage delete request (challenge/confirm)"
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/schemas.yaml#/components/schemas/OwnerStorageDeleteRequest"
      responses:
        "200":
          description: Storage deleted (confirmation)
          content:
            application/json:
              schema:
                $ref: "./schemas/schemas.yaml#/components/schemas/APIResponseModel"
        "204":
          description: Storage deleted (no content)
components:
  securitySchemes:
    SessionTokenAuth:
      type: apiKey
      in: header
      name: Session-Token
      description: Session token for authentication (starts with 'sessiontok_')
